// node scripts/demo-svg.mjs → docs/demo.svg
// Runs the real `kv` (dist/cli.js) against a temporary vault and draws a terminal from what it actually
// prints — nothing is typed by hand. Needs a build (npm run build) and, to unlock without a terminal,
// "remember me": DPAPI on Windows, the keychain elsewhere.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = path.resolve(import.meta.dirname, "..");
const HOME = fs.mkdtempSync(path.join(os.tmpdir(), "kv-demo-"));
const REPO = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "kv-demo-repo-")), "my-app");
fs.mkdirSync(REPO);
const env = { ...process.env, KV_HOME: HOME, KV_LANG: "en", NO_COLOR: "1" };
const CLI = path.join(ROOT, "dist/cli.js");

// a vault with made-up demo values, remembered so kv can unlock without a prompt
execFileSync(
  process.execPath,
  [
    "--experimental-strip-types",
    "--no-warnings=ExperimentalWarning",
    "--input-type=module",
    "-e",
    `
  import * as s from ${JSON.stringify(pathToFileURL(path.join(ROOT, "src/store.ts")).href)};
  import * as r from ${JSON.stringify(pathToFileURL(path.join(ROOT, "src/remember.ts")).href)};
  const { key } = await s.create("demo only"); await r.remember(key, s.salt());`,
  ],
  { env },
);
execFileSync("git", ["init", "-q"], { cwd: REPO });
fs.writeFileSync(path.join(REPO, "package.json"), JSON.stringify({ name: "my-app" }));

/** Run kv as the demo shows it; stdout and stderr together, paths shortened */
const steps = [];
const both = (shown, args, input) => {
  const p = execFileSync(
    process.execPath,
    [
      "-e",
      `
    const { spawnSync } = require("node:child_process");
    const r = spawnSync(process.execPath, ${JSON.stringify([CLI, ...args])}, { cwd: ${JSON.stringify(REPO)}, input: ${JSON.stringify(input ?? "")}, encoding: "utf8" });
    process.stdout.write((r.stdout || "") + (r.stderr || ""));`,
    ],
    { env, encoding: "utf8" },
  );
  return { cmd: shown, out: p.replace(/\r/g, "").trimEnd().replaceAll(HOME, "~/.keyvault").replaceAll(REPO, "~/my-app").replaceAll("~/my-app\\", "~/my-app/") };
};

steps.push(both("kv init-project", ["init-project"]));
steps.push(both("echo sk_live_8f2c… | kv set my-app/STRIPE_KEY", ["set", "my-app/STRIPE_KEY"], "sk_live_8f2cd94e7a1b"));
steps.push(both("echo postgres://… | kv set my-app/DATABASE_URL", ["set", "my-app/DATABASE_URL"], "postgres://app:pw@db.internal/app"));
steps.push(both("kv ls", ["ls"]));
steps.push(
  both("kv run -- node -e \"console.log(Object.keys(process.env).filter(k => k.startsWith('STRIPE')))\"", [
    "run",
    "--",
    process.execPath,
    "-e",
    "console.log(Object.keys(process.env).filter(k => k.startsWith('STRIPE')))",
  ]),
);
fs.writeFileSync(path.join(REPO, "config.js"), 'export const stripe = "sk_live_8f2cd94e7a1b";\n');
execFileSync("git", ["add", "config.js"], { cwd: REPO });
steps.push(both("git add config.js && kv guard", ["guard"]));

// ── render ──
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const lines = [];
for (const s of steps) {
  lines.push({ text: `$ ${s.cmd}`, cls: "cmd" });
  for (const l of s.out.split("\n")) if (l.trim()) lines.push({ text: l, cls: /stopped|found/.test(l) ? "warn" : "out" });
  lines.push({ text: "", cls: "out" });
}
lines.pop();
const LH = 20;
const W = 860;
const H = 52 + lines.length * LH + 16;
const body = lines
  .map((l, i) => `<text x="20" y="${60 + i * LH}" class="${l.cls}">${esc(l.text.length > 104 ? `${l.text.slice(0, 103)}…` : l.text)}</text>`)
  .join("\n  ");
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="kv-vault in a terminal">
  <style>
    text { font: 13px ui-monospace, "Cascadia Mono", Consolas, "SF Mono", Menlo, monospace; white-space: pre; }
    .cmd { fill: #e6edf3; font-weight: 600; } .out { fill: #9aa4b0; } .warn { fill: #f0a868; }
  </style>
  <rect width="${W}" height="${H}" rx="10" fill="#14171d"/>
  <circle cx="22" cy="20" r="6" fill="#ff5f57"/><circle cx="42" cy="20" r="6" fill="#febc2e"/><circle cx="62" cy="20" r="6" fill="#28c840"/>
  <text x="${W / 2}" y="24" text-anchor="middle" class="out">kv-vault — real output, generated by scripts/demo-svg.mjs</text>
  ${body}
</svg>
`;
fs.mkdirSync(path.join(ROOT, "docs"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "docs/demo.svg"), svg);
console.log(`docs/demo.svg — ${lines.length} lines`);
fs.rmSync(HOME, { recursive: true, force: true });
